#development:
#  :address: smtp.gmail.com
#  :port: 587
#  :authentication: plain
#  :user_name: <%= ENV["EMAIL_ACCOUNT"] %>
 # :password: <%= ENV["MAIL_PSWD"] %>
#  :enable_starttls_auto: true
#production:
#  :address: smtp.gmail.com
 # :port: 587
#  :authentication: plain
 # :user_name: <%= ENV["EMAIL_ACCOUNT"] %>
 # :password: <%= ENV["MAIL_PSWD"] %>
 # :enable_starttls_auto: true