development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: enteryouremailhere@example.com
  :password: enteryourpasswordhere
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: enteryouremailhere@example.com
  :password: enteryourpasswordhere
  :enable_starttls_auto: true